language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

intall:
   - npm install -D
   - cd ./tests/smoke/template
   - npm install -D
   - cd ../../../

scripts:
    - npm run test:unit